project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: work-experience.qmd
        text: Work Experience
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: education.qmd
        text: Education

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
